#ifndef GLOBALS_H
#define GLOBALS_H
extern const int RitReadPin;
extern int RitReadValue;
extern int RitFreqOffset;
extern const int SmeterReadPin;
extern int SmeterReadValue;
extern const int BatteryReadPin;
extern int BatteryReadValue;
extern const int PowerOutReadPin;
extern int PowerOutReadValue;
extern const int CodeReadPin;
extern int CodeReadValue;
extern const int CWSpeedReadPin;
extern int CWSpeedReadValue;
extern int TX_key;
extern int band_sel;
extern int band_set;
extern int bsm;
extern int Step_Select_Button;
extern int Step_Select_Button1;
extern int Step_Multi_Function_Button;
extern int Step_Multi_Function_Button1;
extern int Selected_BW;
extern int Selected_Step;
extern int Selected_Other;
extern const int encoder0PinA;
extern const int encoder0PinB;
extern int val;
extern int encoder0Pos;
extern int encoder0PinALast;
extern int n;
extern const long meter_40;
extern const long meter_20;
extern const long Reference;
extern long RIT_frequency;
extern long RX_frequency;
extern long save_rec_frequency;
extern long frequency_step;
extern long frequency;
extern long frequency_old;
extern long frequency_tune;
extern long frequency_default;
extern long fcalc;
extern long IF;
extern unsigned long loopCount;
extern unsigned long lastLoopCount;
extern unsigned long loopsPerSecond;
extern unsigned int printCount;
extern unsigned long loopStartTime;
extern unsigned long loopElapsedTime;
extern float loopSpeed;
extern unsigned long LastFreqWriteTime;
#endif
