#include "globals.h"
#include "defines.h"

bool getDitKey();
bool getDahKey();
void pollRotaryEncoder();
void pollRIT();
void Step_Flash();
void stop_led_on();
void stop_led_off();
void pollMultifunctionButton();
void Step_Function();
void pollSelectButton();
void Step_Select();
void MF_G();
void MF_Y();
void MF_R();
void S_G();
void S_Y();
void S_R();
void Band_Width_W();
void Band_Width_M();
void Band_Width_N();
void Step_Size_100();
void Step_Size_1k();
void Step_Size_10k();
void Other_1();
void Other_2();
void Other_3();
